packages:
  - "packages/*"
allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - '@ochibi/runtime@0.1.0'
  - '@chibi3d/runtime@0.2.0'
